# This workflow adds info about each merged PR to release draft
env:
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  COMMIT_AUTHOR: ${{ github.event.head_commit.author }}
  COMMIT_LABELS: ${{ github.event.label.name }}
  GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}

name: Add_PR_to_ReleaseDraft

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create/Update release draft  
      shell: pwsh
      run: ./scripts/mergedPRDetailsToReleaseDraft -CommitMessage "$env:COMMIT_MESSAGE" -CommitAuthor "$env:COMMIT_AUTHOR" -CommitLabels "$env:COMMIT_LABELS" -Token "$env:GITHUB_TOKEN"
