# This workflow adds info about each merged PR to release draft
env:
  PR_NUMBER: ${{ github.event.number }}
  PR_TITLE: ${{ github.event.pull_request.title }}
  GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}

name: Add_PR_to_ReleaseDraft

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create/Update release draft  
      shell: pwsh
      run: ./scripts/prMessageToRelaseDraft.ps1 -PRNumber "$env:PR_NUMBER" -PRTitle "$env:PR_TITLE" -Token "$env:GITHUB_TOKEN"